#include "adc_ctrl.h"

/* These handles are generated by CubeMX from SMART_EDB_BOARD.ioc. */
extern ADC_HandleTypeDef hadc1;
extern ADC_HandleTypeDef hadc2;
extern TIM_HandleTypeDef htim6;

static uint16_t adc1_dma_buffer[ADC_CTRL_DMA_SAMPLE_COUNT] __ALIGNED(4);
static bool adc1_running;

void ADC_CTRL_Init(void)
{
    adc1_running = false;

    (void)HAL_ADCEx_Calibration_Start(&hadc1, ADC_SINGLE_ENDED);
    (void)HAL_ADCEx_Calibration_Start(&hadc2, ADC_SINGLE_ENDED);
    (void)ADC_CTRL_Start();
}

bool ADC_CTRL_Start(void)
{
    if (adc1_running)
    {
        return true;
    }

    if (HAL_ADC_Start_DMA(&hadc1, (uint32_t *)adc1_dma_buffer,
                          ADC_CTRL_DMA_SAMPLE_COUNT) != HAL_OK)
    {
        return false;
    }

    if (HAL_TIM_Base_Start(&htim6) != HAL_OK)
    {
        (void)HAL_ADC_Stop_DMA(&hadc1);
        return false;
    }

    adc1_running = true;
    return true;
}

void ADC_CTRL_Stop(void)
{
    if (adc1_running)
    {
        (void)HAL_ADC_Stop_DMA(&hadc1);
        (void)HAL_TIM_Base_Stop(&htim6);
        adc1_running = false;
    }
}

uint16_t ADC_CTRL_GetADC1Latest(void)
{
    uint32_t remaining;
    uint32_t index;

    if (!adc1_running || (hadc1.DMA_Handle == NULL))
    {
        return 0U;
    }

    remaining = __HAL_DMA_GET_COUNTER(hadc1.DMA_Handle);
    index = (ADC_CTRL_DMA_SAMPLE_COUNT - remaining) % ADC_CTRL_DMA_SAMPLE_COUNT;
    index = (index == 0U) ? (ADC_CTRL_DMA_SAMPLE_COUNT - 1U) : (index - 1U);
    return adc1_dma_buffer[index];
}

uint16_t ADC_CTRL_GetADC1Average(void)
{
    uint32_t sum = 0U;
    uint32_t i;

    if (!adc1_running)
    {
        return 0U;
    }

    for (i = 0U; i < ADC_CTRL_DMA_SAMPLE_COUNT; ++i)
    {
        sum += adc1_dma_buffer[i];
    }

    return (uint16_t)(sum / ADC_CTRL_DMA_SAMPLE_COUNT);
}

bool ADC_CTRL_ReadADC2Raw(uint16_t *raw, uint32_t timeout_ms)
{
    HAL_StatusTypeDef status;

    if (raw == NULL)
    {
        return false;
    }

    status = HAL_ADC_Start(&hadc2);
    if (status != HAL_OK)
    {
        return false;
    }

    status = HAL_ADC_PollForConversion(&hadc2, timeout_ms);
    if (status == HAL_OK)
    {
        *raw = (uint16_t)HAL_ADC_GetValue(&hadc2);
    }

    (void)HAL_ADC_Stop(&hadc2);
    return (status == HAL_OK);
}
